# This is a basic workflow to help you get started with Actions

name: GenerateResume

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Installs Python
      - name: Setup Python
        uses: actions/setup-python@v5.2.0
      
      # Installs AWS-CLI
      - name: Install AWS-CLI
        run: pip -m aws-shell
      
      # Installs Tex-Live
      - name: Install Tex-Live
        run: sudo apt-get install -y texlive
        
      # Runs a single command using the runners shell
      - name: Clone Resume Generator repo into runner
        run: git clone https://github.com/ethanr555/Resume-Generator

      - name: Generate Script
        run: python Resume-Generator/ResumeAssembler.py portfolio.json

      - name: Upload Resume to S3
        run: aws s3 cp resume.pdf s3://ethanrportfoliowebsite/resume.pdf
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
          AWS_DEFAULT_REGION: 'us-west-1'

      - name: Upload Resume
        uses: actions/upload-artifact@v4.4.3
        with:
          name: Resume.pdf
          path: resume.pdf
          retention-days: 1
